### PR TITLE
Vite -> NextJS conversion

### PR DESCRIPTION
**Pull request by SevLG**
NextJS app working, has some weird warnings (in terminal) when using the plot page but seems to be working as it should. Tried to look into it but couldn't find how to fix it, not sure if it will be a problem.

### CODE REVIEW

**Comment by SevLG** [comment]
Forgot to do npm run build, need to fix the ESLint warnings

**Comment by JanProgrammierung** [comment]
Looks good!
Some code broke though, f.ex. the header is already in responsive / mobile view only having a 13 inch laptop.
That can be fixed by adding
`screens: {
          '13inch': '1440px',  // Customize this value based on the resolution you target
        },`
to the tailwind config theme extend part. (Same as in old vite tailwind config js)


Also the download radio button selection does not work fully correct anymore. I've seen you changed the download button boxes dependencies. I guess it's related to that. Was it required by ESLint to change those?

**Review by JanProgrammierung — CHANGES_REQUESTED** [review]
Looks good!
Some code broke though, f.ex. the header is already in responsive / mobile view only having a 13 inch laptop.
That can be fixed by adding
`screens: {
          '13inch': '1440px',  // Customize this value based on the resolution you target
        },`
to the tailwind config theme extend part. (Same as in old vite tailwind config js)


Also the download radio button selection does not work fully correct anymore. I've seen you changed the download button boxes dependencies. I guess it's related to that. Was it required by ESLint to change those?

**Review by JanProgrammierung — APPROVED** [review]

**Comment by JanProgrammierung** [comment]
Can be merged

**Pull request merged**
